version: '3.8'
services:
  postgres:
    image: postgres:15.4
    container_name: softmarket-db
    restart: always
    environment:
      POSTGRES_USER: apisoftmarket
      POSTGRES_PASSWORD: softmarket
      POSTGRES_DB: apisoftmarket
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U apisoftmarket"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    build: .
    container_name: softmarket-api
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/apisoftmarket
      SPRING_DATASOURCE_USERNAME: apisoftmarket
      SPRING_DATASOURCE_PASSWORD: softmarket
    restart: unless-stopped
volumes:
  postgres_data: