spring:
  datasource:
    url: jdbc:postgresql://ep-rapid-grass-a4m42ube-pooler.us-east-1.aws.neon.tech/neondb
    username: neondb_owner
    password: npg_29oYLCIbMuvF
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      idle-timeout: 180000
      max-lifetime: 300000
      leak-detection-threshold: 60000
      connection-test-query: SELECT 1
      validation-timeout: 3000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: false
  webflux:
    timeout: 60s
  reactor:
    netty:
      connection-timeout: 20s
      read-timeout: 60s
      write-timeout: 60s

      pool:
        max-connections: 50
        max-idle-time: 15s
        max-life-time: 30s
        acquire-timeout: 30s
        evict-in-background: 5s

server:
  port: 8080
  error:
    include-message: always

external-api:
  connection:
    timeout: 20s
    read-timeout: 60s
    max-retries: 1
    retry-delay: 2s
  authUrl: https://api-sandbox.factus.com.co/oauth/token
  facturaUrl: https://api-sandbox.factus.com.co/v1/bills/validate
  rangoEnumeracionUrl: https://api-sandbox.factus.com.co/v1/numbering-ranges

