spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/apisoftmarket
    username: apisoftmarket
    password: softmarket
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  error:
    include-message: always

external-api:
  authUrl: https://api-sandbox.factus.com.co/oauth/token
  facturaUrl: https://api-sandbox.factus.com.co/v1/bills/validate
