spring:
  data:
    mongodb:
      uri: mongodb://apisoftmarket:softmarket@localhost:27017/apisoftmarketmongo

server:
  port: 8080
  error:
    include-message: always

external-api:
  connection:
    timeout: 20s
    read-timeout: 60s
    max-retries: 1
    retry-delay: 2s
  authUrl: ${AUTHURL}
  facturaUrl: ${FACTURAURL}
  rangoEnumeracionUrl: ${RANGOENUMERACIONURL}
  descargarFacturaUrl: ${DESCARGARFACTURAURL}
  githubToken: ${GITHUBTOKEN}
  githubOwner: ${GITHUBOWNER}
  githubRepo: ${GITHUBREPO}
  nameAuthorizationGoogle: ${NAMEAUTHORIZATIONGOOGLE}
  urlGithub: ${URLGITHUB}
  folderIdDrive: ${FOLDERIDDRIVE}