spring:
  datasource:
    url: jdbc:postgresql://ep-rapid-grass-a4m42ube-pooler.us-east-1.aws.neon.tech/neondb
    username: neondb_owner
    password: npg_29oYLCIbMuvF
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
server:
  error:
    include-message: always

external-api:
  authUrl: https://api-sandbox.factus.com.co/oauth/token
  facturaUrl: https://api-sandbox.factus.com.co/v1/bills/validate

